### ISSUE TITLE
Dockerise codenjoy 

### ISSUE THREAD

**Issue by rohitvvv** [codenjoyme/codenjoy#11]
Dockerising codenjoy platform will enable one to quickly spin up a container and start the event. 
Bringing up the mvn build takes time and having a docker image with deployable artefacts will significantly speed up server boot time. 
1. A docker image with deployable artefacts(fast)
2. A docker image which builds the latest code pulled from Git and then builds an image from it. (slow)

**Comment by rohitvvv** [comment]
I would like to work on this along with other interested collaborators.

**Comment by rohitvvv** [comment]
I was able to dockerize portable version of bomber man. 
$docker run -p 8080:8080 rohitvvv/bomb
This makes running codenjoy events simple. All you need is docker and no need to run maven builds which take up lot of time.

**Comment by codenjoyme** [comment]
Rohit, Thanks a lot! I will continue for codenjoy with any game

**Comment by codenjoyme** [comment]
Hello Rohit, done 
https://github.com/codenjoyme/codenjoy/tree/master/CodingDojo/docker-library
Now you can build the codenjoy with the given games 
`docker build -t apofig/codenjoy-source . --build-arg GAMES=snake,bomberman,sample --build-arg SKIP_TESTS=true`
..or all games 
`docker build -t apofig/codenjoy-source . --build-arg SKIP_TESTS=true`
Then 
`docker run --name codenjoy -d -p 80:8080 apofig/codenjoy-source`
