### ISSUE TITLE
Round settings by default should be disabled

### ISSUE THREAD

**Issue by codenjoyme** [codenjoyme/codenjoy#135]
Вот тут
https://github.com/codenjoyme/codenjoy/blob/master/CodingDojo/games/engine/src/main/java/com/codenjoy/dojo/services/round/RoundSettings.java#L104

Соответственно во всех тестах которые могут слететь потому что рассчитывают что оно включено, надо в TestSameSettings явно установить флаг.

**Comment by rkulyniak** [comment]
There are some tests that depend on the settings defined in the code. 
We should separate such cases. Tests suppose to have their own settings.

**Comment by codenjoyme** [comment]
Кажется нам надо вмержить эти изменения
https://github.com/codenjoyme/codenjoy/pull/139

Что касается вопроса: каждая игра имеет своий TestGameSettings с базовыми настройками, в которых взято за основу GameSettings и сделано ряд правок для всех тестов. Дальше кажыдый TestCase может сам дополнительно поменять указаные в TestGameSettings сеттинги на свое усмотрение (в setup методе) для всех тестов этого кейза (тестового класса). И третье место - каждый тест может в своем given блоке изменить указанное в setup+TestGameSettings. Три места дают гибкость менять сеттинги так как требуется для задумки тестирования. Если встречается много дублирующихся настроек в given частях тестов, тогда может имеет смысл выделить новый testcase класс со своим setup. Если дублирование встречается в нескольких setup методах, то имеет смысл унести настройки в TestGameSettings. 

В контексте этого тикета важно выключить опцию для всех по умолчанию, а для тестов игрушек, которые ожидают что опци я будет включена включить ее либо в TestGameSettings либо в setup конкретного тестового класса (предпочительнее).
