### ISSUE TITLE
Redesign first game

### ISSUE THREAD

**Issue by codenjoyme** [codenjoyme/codenjoy#144]
Name Molly Mage

Main logo
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/4629949/121739789-c6c46700-cb04-11eb-882e-9f1be42ac7bd.png)

Sprites
![chest](https://user-images.githubusercontent.com/4629949/121739686-aa282f00-cb04-11eb-8f68-72992aa29995.png)
![dead_ghost](https://user-images.githubusercontent.com/4629949/121739691-aa282f00-cb04-11eb-9740-524d71cb15a7.png)
![dead_pumpkin](https://user-images.githubusercontent.com/4629949/121739694-aac0c580-cb04-11eb-86b3-23f834697d87.png)
![explosion](https://user-images.githubusercontent.com/4629949/121739695-aac0c580-cb04-11eb-867b-15610b134acb.png)
![explosion_chest](https://user-images.githubusercontent.com/4629949/121739696-aac0c580-cb04-11eb-899b-18334a359d08.png)
![ghost](https://user-images.githubusercontent.com/4629949/121739697-ab595c00-cb04-11eb-818a-55368248bfcb.png)
![magic flask 1](https://user-images.githubusercontent.com/4629949/121739698-ab595c00-cb04-11eb-8b6f-bb6012df893d.png)
![magic flask 2](https://user-images.githubusercontent.com/4629949/121739699-ab595c00-cb04-11eb-854d-2e702e6dd943.png)
![magic flask_count increase](https://user-images.githubusercontent.com/4629949/121739701-abf1f280-cb04-11eb-9755-ec5e325d16dc.png)
![magic flask_immune](https://user-images.githubusercontent.com/4629949/121739702-abf1f280-cb04-11eb-8a5d-1bb3ee86b192.png)
![magic flask_radius increase](https://user-images.githubusercontent.com/4629949/121739703-abf1f280-cb04-11eb-8303-47f5d1d10d43.png)
![magic flask_remote control](https://user-images.githubusercontent.com/4629949/121739706-ac8a8900-cb04-11eb-8043-696eebb83d7c.png)
![magic flask_timer 1](https://user-images.githubusercontent.com/4629949/121739708-ac8a8900-cb04-11eb-9b24-9cee82960550.png)
![magic flask_timer 2](https://user-images.githubusercontent.com/4629949/121739709-ac8a8900-cb04-11eb-9bea-38fef8cc7ef2.png)
![magic flask_timer 3](https://user-images.githubusercontent.com/4629949/121739710-ad231f80-cb04-11eb-89de-483829d5f1cb.png)
![magic flask_timer 4](https://user-images.githubusercontent.com/4629949/121739711-ad231f80-cb04-11eb-8541-5fa8d18d7c12.png)
![magic flask_timer 5](https://user-images.githubusercontent.com/4629949/121739712-ad231f80-cb04-11eb-89a4-dde1d02e6a9d.png)
![Molly_blue](https://user-images.githubusercontent.com/4629949/121739713-adbbb600-cb04-11eb-9dba-d117e6b923d3.png)
![Molly_pink](https://user-images.githubusercontent.com/4629949/121739715-adbbb600-cb04-11eb-8ae9-03209e83ec42.png)
![none](https://user-images.githubusercontent.com/4629949/121739718-adbbb600-cb04-11eb-9a81-8b663344c689.png)
![open_chest](https://user-images.githubusercontent.com/4629949/121739720-ae544c80-cb04-11eb-9d58-a6fa99d4e125.png)
![pot_blue](https://user-images.githubusercontent.com/4629949/121739721-aeece300-cb04-11eb-83a6-bac6f94bf79b.png)
![pot_darkblue](https://user-images.githubusercontent.com/4629949/121739722-aeece300-cb04-11eb-9d53-0aa8b129de47.png)
![pot_green](https://user-images.githubusercontent.com/4629949/121739724-aeece300-cb04-11eb-96a6-501ccaea5c13.png)
![pot_pink](https://user-images.githubusercontent.com/4629949/121739726-af857980-cb04-11eb-81dd-2d259ee902ac.png)
![pumpkin](https://user-images.githubusercontent.com/4629949/121739727-af857980-cb04-11eb-9c98-cc111a60e7c2.png)
![wall](https://user-images.githubusercontent.com/4629949/121739729-af857980-cb04-11eb-86e9-42afce93bf27.png)
![water](https://user-images.githubusercontent.com/4629949/121739731-b01e1000-cb04-11eb-87c5-64d0dd942ddc.png)

**Comment by rkulyniak** [comment]
redesigned
