### ISSUE TITLE
Session expired on the codenjoy and when following the link to connect to the game

### ISSUE THREAD

**Issue by crazyfairytale** [codenjoyme/codenjoy#151]
**Preconditions:**
- Session expired on the codenjoy

**Steps:**
1. Open the link: https://dojorena.io/codenjoy-contest/board/player/dojorena10?code=5488885478262189869

**Expected result**
Not shows the name and email for sign up

**Actual result**
The name an email are show for sing up
![image](https://user-images.githubusercontent.com/86113110/122567771-dc88dd80-d06a-11eb-8b70-97404c932ae1.png)

P.S. If I change in the URL user ID, I can show names and emails other users

**Comment by rkulyniak** [comment]
fixed
