### ISSUE TITLE
[bug][clifford] Cant drill under robber

### ISSUE THREAD

**Issue by codenjoyme** [codenjoyme/codenjoy#337]
[2021-11-09 09:23] Alma 
За мной бежит бандит и между нами расстояние 2 клетки, хочу выстрелить, разворачиваюсь +1 клетка вперед к бандиту и не успеваю выстрелить на меня уже напал бандит. Это тоже фича?)

**Comment by dp-ua** [comment]
Стрелять можно одновременно с разворотом.
Проблема с грабителем может возникнуть только, если он бежит впритык за гером. 
Если есть хоть минимальная дистанция - возможность для выстрела, чтобы поймать его в яму, есть.
