### ISSUE TITLE
[bug][chat] The message about exceeding the characters in the chat contains a list of the table

### ISSUE THREAD

**Issue by crazyfairytale** [codenjoyme/codenjoy#489]
Когда пользователь отправляет больше 255 символов в чате, то система возвращает сообщение об ошибке в котором содержится запрос SQL со списком столбцов

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/86113110/160109888-5fa56157-8136-4b3a-9daf-011a5e33b8f7.png)

**Comment by codenjoyme** [comment]
Now it will be
![image](https://user-images.githubusercontent.com/4629949/161435188-2fbe3de5-6da1-4b1a-8a6e-7f8c286b5543.png)

**Comment by codenjoyme** [comment]
![image](https://user-images.githubusercontent.com/4629949/161435434-b3d8a6d4-1fd2-4d90-815d-0bdd23c7842a.png)
If debug disabled

**Comment by codenjoyme** [comment]
![image](https://user-images.githubusercontent.com/4629949/161435492-84e9db10-8a02-4f65-9af4-87c2265c19b4.png)
if debug enabled
