### ISSUE TITLE
Getting 404 error

### ISSUE THREAD

**Issue by RajeevKumarMarrapu** [codenjoyme/codenjoy#87]
When I open localhost:8080 in local it will throw 404 error. Instead it would be good if we can provide all login/register, help and more info about the dojo etc. in the welcome page.

**Comment by codenjoyme** [comment]
Please try
http://localhost:8080/codenjoy-contest

**Comment by codenjoyme** [comment]
Please try
http://localhost:8080/codenjoy-contest

пн, 2 нояб. 2020 г. в 13:18, RajeevKumarMarrapu <notifications@github.com>:

**Comment by RajeevKumarMarrapu** [comment]
Yes it will work but when I deployed in an environment and give it others they should be able understand without having know these urls

**Comment by codenjoyme** [comment]
We have linux sctipt to build server on this OS 
https://github.com/codenjoyme/codenjoy-portable-linux
There is nginx. It will care about this (and other things like SSL, domain name, enable/disable usefull components)
Please read this manual https://github.com/codenjoyme/codenjoy-portable-linux#ubuntu-portable-script
